package com.filemark.utils;

import java.util.Arrays;
import java.util.Collection;

public class SmartiConstant {
	public static String APP="app";
	public static String DRAW="draw";
	public static String FOLD="fold";
	public static String DOC="doc";
	public static String PAGES="pages";
	public static String PAGETYPE="page_type";
	public static String DEVICE="device";
	public static String DISPOSITION="ifm_dispositions";
	public static String RECORDCLASS="record_class";
	public static String RECORDINDEX="record_index";
	public static String COLDINDEX="cold_index";
	public static String COLDREPORT="cold_report";
	public static String COLDFORMS="cold_forms";
	public static String COLDFIELDS="cold_fields";
	public static String COLDSOURCE="cold_source";
	public static String EXTERNALFILE="external_file";
	public static String FILEIMPORT="file_import";
	public static String PAGEIMPORT="page_import";
	public static String SAVEDNAMES="savednames";
	public static String EVENTGROUPS="eventgroups";
	public static String EVENTGROUPNAMES="eventgroupnames";
	public static String USAGELOG="usagelog";
	public static String TRANSTABLES="trans_tables";
	public static String[] LEVELTOTABLE={"app.name","draw.name","fold.name","doc.name","page.index1","page.index2","page.index3","page.index4","page.index5","page.index6","page.id","content","note","doc.createDate","page.id.pageNum","ci.id.name","ci.id.name"};
	public static String[] LEVELTOINDEX={"doc.fold.draw.app.name","doc.fold.draw.name","doc.fold.name","doc.name","page.index1","page.index2","page.index3","page.index4","page.index5","page.index6","id","content","note"};
	public static String[] OPERATORS={"LIKE","NOT LIKE","BEGINS WITH","ENDS WITH","CONTAINS","BETWEEN","=",">","<",">=","<=","<>","IS","IS NOT"};
	public static String FROMCOLUMNINDX = "from ColumnIdx ci join ci.pages page join page.doc doc join doc.fold fold join fold.draw draw join draw.app app where ";
	public static String FROMEXTERNALFILE = "select distinct ext from ExternalFile ext left join ext.pageses page left join page.doc doc left join page.pageType type left join doc.fold fold left join fold.draw draw left join draw.app app where page.indexed = 1 and page.deleted is null and doc.deleted is null ";
	public static String FROMPAGE = "from Pages page join page.doc doc join doc.fold fold join fold.draw draw join draw.app app where ";
	public static String FROMDOC = "from Doc doc left join doc.fold fold left join fold.draw draw left join draw.app app where ";
	public static String FROMFOLD = "from Fold fold left join fold.draw draw left join draw.app app where ";
	public static String FROMDRAW = "from Draw draw left join draw.app app where ";
	public static String FROMAPP = "from App app where ";
	public static String DOCACTION     = "#{0:'Forwarding',2:'Auto Filled',4:'Do not Index',6:'Import'}";
	public static String PAGEACTION    = "#{0:'Forwarding',1:'As is',2:'Auto Filled',4:'Do not Index',6:'Import'}";
	public static int    FORWARDING = 0;
	public static int    ASIT = 1;
	public static int    AUTOFILL = 2;
	public static int    LIST = 3;
	public static int    SKIP = 4;
	public static int    ABORT = 5;
	public static int    IMPORT = 6;
	public static int    NOTFOUND = 0;
	public static int    WAITING = 1;
	public static int    INDEXING = 2;
	public static int    FAILURE = 3;
	public static int    IMPORTED = 4;
	public static int    SUCCESS = 5;
	public static int    LOGIN = 101;
	public static int    LOGOUT = 102;	
	public static int    SIMPLEINDEX = 103;	
	public static int    EMAILDS = 104;	
	public static int    AUTOINDEX = 105;	
	public static int    PURGE = 106;
	public static int    SELECTAPP = 110;
	public static int    OPENPAGE = 111;
	public static int    IMPORTFILE = 114;
	public static int    TEXT2PDF = 115;
	public static int    ERROR = 120;
	public static int    DELETE = 121;
	public static int    UPDATE = 122;
	public static int    RESTORE = 123;
	public static int    IMF = 124;	
}
