package com.filemark.jcr.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;

// Generated 18-Jul-2009 9:35:14 PM by Hibernate Tools 3.2.4.GA

/**
 * Smartgroups generated by hbm2java
 */
@Entity
public class Smartgroups implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String groupName;
	private int id;
	private Set<Smartusers> smartusers =new HashSet<Smartusers>(0);
	private Date createDate;
	public Smartgroups() {
	}

	
/*	
	public Smartgroups(String groupName) {
		super();
		this.groupName = groupName;
	}

*/




	public Set<Smartusers> getSmartusers() {
		return smartusers;
	}



	public void setSmartusers(Set<Smartusers> smartusers) {
		this.smartusers = smartusers;
	}




	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((groupName == null) ? 0 : groupName.hashCode());
		result = prime * result + id;
		return result;
	}



	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Smartgroups other = (Smartgroups) obj;
		if (groupName == null) {
			if (other.groupName != null)
				return false;
		} else if (!groupName.equals(other.groupName))
			return false;
		if (id != other.id)
			return false;
		return true;
	}



	public int getId() {
		return id;
	}



	public void setId(int id) {
		this.id = id;
	}



	public String getGroupName() {
		return groupName;
	}



	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}



	public Date getCreateDate() {
		return createDate;
	}



	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
	
	
}
